swagger: "2.0"
info:
  description: "This is the api doc for some example APIs running on one http server"
  version: ""
  title: "Swagger Simple Http Server"
host: "localhost:9091"
paths:
  "/simple":
    post:
      tags:
      - "simple"
      summary: ""
      description: "this api check header, check body json, and returned given string to client"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: body
          name: message
          description: Message to send to simple api.
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      responses:
        200:
          description: A JSON object
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string
        400:
          description: "Bad Request"
  "/value-holder":
      post:
        tags:
        - "value-holder"
        summary: "send data to server"
        description: "this api check header, check body json, and hold/save sent data temporarily until shutdown"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
          - name: id
            in: query
            type: string
            description: >
               it is needed to save data as its key.
          - in: body
            name: message
            description: data to send to value-holder api (name, role) and will be put to map with id from http query.
            schema:
              type: object
              required:
                - message
              properties:
                name:
                  type: string
                role:
                  type: string
        responses:
          '200':
            description: http status ok
          '400':
            description: "Bad Request"
      get:
        tags:
        - "value-holder"
        summary: "get data from server by given id (previously sent to POST /value-handler)"
        description: "this api check header and return data by id"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
          - name: id
            in: query
            type: string
            description: >
               it is needed to get saved data.
        responses:
          200:
            description: A JSON object containing id, name, and role
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                role:
                  type: string
          400:
            description: "Bad Request"